- name: Deploy test.html using Ansible
  hosts: all
  become: true
  tasks:
    - name: Install Apache Web Server
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes  
    - name: Remove default Apache index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent     

    - name: Copy HTML file to web root
      ansible.builtin.copy:
        src: test.html
        dest: /var/www/html/test.html 

    - name: Start Apache service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
